<?php

define( 'APERITIF_MEMBERSHIP_VERSION', '1.0' );
define( 'APERITIF_MEMBERSHIP_ABS_PATH', dirname( __FILE__ ) );
define( 'APERITIF_MEMBERSHIP_REL_PATH', dirname( plugin_basename( __FILE__ ) ) );
define( 'APERITIF_MEMBERSHIP_URL_PATH', plugin_dir_url( __FILE__ ) );
define( 'APERITIF_MEMBERSHIP_ASSETS_PATH', APERITIF_MEMBERSHIP_ABS_PATH . '/assets' );
define( 'APERITIF_MEMBERSHIP_ASSETS_URL_PATH', APERITIF_MEMBERSHIP_URL_PATH . 'assets' );
define( 'APERITIF_MEMBERSHIP_INC_PATH', APERITIF_MEMBERSHIP_ABS_PATH . '/inc' );
define( 'APERITIF_MEMBERSHIP_INC_URL_PATH', APERITIF_MEMBERSHIP_URL_PATH . 'inc' );
define( 'APERITIF_MEMBERSHIP_LOGIN_MODAL_PATH', APERITIF_MEMBERSHIP_INC_PATH . '/login-modal' );
define( 'APERITIF_MEMBERSHIP_LOGIN_MODAL_URL_PATH', APERITIF_MEMBERSHIP_INC_URL_PATH . 'login-modal' );