<?php
$color_selector                      = array(
	'.qodef-h1 a:hover',
	'h1 a:hover',
	'.qodef-h2 a:hover',
	'h2 a:hover',
	'.qodef-h3 a:hover',
	'h3 a:hover',
	'.qodef-h4 a:hover',
	'h4 a:hover',
	'.qodef-h5 a:hover',
	'h5 a:hover',
	'.qodef-h6 a:hover',
	'h6 a:hover',
	'a:hover',
	'p a:hover',
	'#qodef-page-header .widget_icl_lang_sel_widget .wpml-ls-legacy-dropdown .wpml-ls-item-toggle:hover',
	'#qodef-page-header .widget_icl_lang_sel_widget .wpml-ls-legacy-dropdown-click .wpml-ls-item-toggle:hover',
	'#qodef-page-header .widget_icl_lang_sel_widget .wpml-ls-legacy-dropdown .wpml-ls-sub-menu .wpml-ls-item a:hover',
	'#qodef-page-header .widget_icl_lang_sel_widget .wpml-ls-legacy-dropdown-click .wpml-ls-sub-menu .wpml-ls-item a:hover',
	'#qodef-page-header .widget_icl_lang_sel_widget .wpml-ls-legacy-list-horizontal ul li a:hover',
	'#qodef-page-header .widget_icl_lang_sel_widget .wpml-ls-legacy-list-vertical ul li a:hover',
	'#qodef-page-mobile-header .widget_icl_lang_sel_widget .wpml-ls-legacy-dropdown .wpml-ls-item-toggle:hover',
	'#qodef-page-mobile-header .widget_icl_lang_sel_widget .wpml-ls-legacy-dropdown-click .wpml-ls-item-toggle:hover',
	'#qodef-page-mobile-header .widget_icl_lang_sel_widget .wpml-ls-legacy-dropdown .wpml-ls-sub-menu .wpml-ls-item a:hover',
	'#qodef-page-mobile-header .widget_icl_lang_sel_widget .wpml-ls-legacy-dropdown-click .wpml-ls-sub-menu .wpml-ls-item a:hover',
	'#qodef-page-mobile-header .widget_icl_lang_sel_widget .wpml-ls-legacy-list-horizontal ul li a:hover',
	'#qodef-page-mobile-header .widget_icl_lang_sel_widget .wpml-ls-legacy-list-vertical ul li a:hover',
	'#qodef-page-sidebar .widget_icl_lang_sel_widget .wpml-ls-legacy-dropdown .wpml-ls-item-toggle:hover',
	'#qodef-page-sidebar .widget_icl_lang_sel_widget .wpml-ls-legacy-dropdown-click .wpml-ls-item-toggle:hover',
	'#qodef-page-sidebar .widget_icl_lang_sel_widget .wpml-ls-legacy-dropdown .wpml-ls-sub-menu .wpml-ls-item a:hover',
	'#qodef-page-sidebar .widget_icl_lang_sel_widget .wpml-ls-legacy-dropdown-click .wpml-ls-sub-menu .wpml-ls-item a:hover',
	'#qodef-page-sidebar .widget_icl_lang_sel_widget .wpml-ls-legacy-list-horizontal ul li a:hover',
	'#qodef-page-sidebar .widget_icl_lang_sel_widget .wpml-ls-legacy-list-vertical ul li a:hover',
	'#qodef-page-footer .widget_icl_lang_sel_widget .wpml-ls-legacy-dropdown .wpml-ls-item-toggle:hover',
	'#qodef-page-footer .widget_icl_lang_sel_widget .wpml-ls-legacy-dropdown-click .wpml-ls-item-toggle:hover',
	'#qodef-page-footer .widget_icl_lang_sel_widget .wpml-ls-legacy-dropdown .wpml-ls-sub-menu .wpml-ls-item a:hover',
	'#qodef-page-footer .widget_icl_lang_sel_widget .wpml-ls-legacy-dropdown-click .wpml-ls-sub-menu .wpml-ls-item a:hover',
	'#qodef-side-area .widget_icl_lang_sel_widget .wpml-ls-legacy-dropdown .wpml-ls-item-toggle:hover',
	'#qodef-side-area .widget_icl_lang_sel_widget .wpml-ls-legacy-dropdown-click .wpml-ls-item-toggle:hover',
	'#qodef-side-area .widget_icl_lang_sel_widget .wpml-ls-legacy-dropdown .wpml-ls-sub-menu .wpml-ls-item a:hover',
	'#qodef-side-area .widget_icl_lang_sel_widget .wpml-ls-legacy-dropdown-click .wpml-ls-sub-menu .wpml-ls-item a:hover',
	'#qodef-404-page .qodef-404-text',
	'.qodef-blog article .qodef-e-info .qodef-e-info-item',
	'.qodef-blog article .qodef-e-info .qodef-e-info-item a',
	'.qodef-blog article .qodef-e-single-links>span:not(.qodef-e-single-links-title)',
	'.qodef-blog article.format-link .qodef-e-link-title',
	'.qodef-blog article.format-quote .qodef-e-quote-author-position',
	'#qodef-page-comments-list .qodef-comment-item .qodef-e-date a',
	'#qodef-mobile-header-navigation ul li a:hover',
	'#qodef-mobile-header-navigation ul li.current-menu-ancestor>a',
	'#qodef-mobile-header-navigation ul li.current-menu-item>a',
	'.qodef-header-navigation ul li.qodef-menu-item--narrow ul li.current-menu-ancestor>a',
	'.qodef-header-navigation ul li.qodef-menu-item--narrow ul li.current-menu-item>a',
	'.qodef-header-navigation ul li.qodef-menu-item--narrow ul li.current-menu-ancestor>a>span',
	'.qodef-header-navigation ul li.qodef-menu-item--narrow ul li.current-menu-item>a>span',
	'.qodef-header-navigation ul li.qodef-menu-item--narrow ul li a:hover',
	'.qodef-header-navigation ul li.qodef-menu-item--narrow ul li.menu-item-has-children:hover:after',
	'#qodef-author-info .qodef-m-country',
	'#qodef-author-info .qodef-m-dob',
	'#qodef-author-info .qodef-m-position',
	'#qodef-author-info .qodef-m-social-icons a',
	'.qodef-header--light:not(.qodef-fullscreen-menu--opened) .qodef-fullscreen-menu-opener:hover',
	'.qodef-fullscreen-menu--opened .qodef-fullscreen-menu-opener',
	'.qodef-header--centered.qodef-header--light #qodef-page-header>div:not(.qodef-header-sticky) .widget:hover',
	'.qodef-header--divided.qodef-header--light #qodef-page-header>div:not(.qodef-header-sticky) .widget:hover',
	'.qodef-header--standard.qodef-header--light #qodef-page-header>div:not(.qodef-header-sticky) .widget:hover',
	'.qodef-header--centered.qodef-header--light #qodef-page-header>div:not(.qodef-header-sticky) .widget:hover a',
	'.qodef-header--divided.qodef-header--light #qodef-page-header>div:not(.qodef-header-sticky) .widget:hover a',
	'.qodef-header--standard.qodef-header--light #qodef-page-header>div:not(.qodef-header-sticky) .widget:hover a',
	'.qodef-header--vertical.qodef-header--light .qodef-vertical-widget-holder .widget a',
	'.qodef-header--vertical.qodef-header--light .qodef-vertical-widget-holder .widget span',
	'.qodef-header--vertical.qodef-header--dark .qodef-vertical-widget-holder .widget a',
	'.qodef-header--vertical.qodef-header--dark .qodef-vertical-widget-holder .widget span',
	'.qodef-header--vertical .qodef-header-vertical-navigation ul li a:hover',
	'.qodef-header--vertical .qodef-header-vertical-navigation ul li.current-menu-ancestor>a',
	'.qodef-header--vertical .qodef-header-vertical-navigation ul li.current-menu-item>a',
	'.qodef-header--vertical .qodef-header-vertical-navigation ul li.current_page_item>a',
	'.qodef-header-navigation ul li.qodef-menu-item--wide .qodef-drop-down-second .qodef-drop-down-second-inner ul li a:hover',
	'.qodef-restaurant-menu-list .qodef-e-description',
	'.qodef-testimonials-list .qodef-e-media-image .qodef-e-media-quote',
	'.qodef-testimonials-list .qodef-e-author .qodef-e-author-job',
	'.qodef-search-cover input[type=text]:focus',
	'.qodef-banner .qodef-m-content .qodef-m-content-inner .qodef-m-text-field',
	'.qodef-pricing-table .qodef-m-inner .qodef-m-price .qodef-m-price-currency',
	'.qodef-pricing-table .qodef-m-inner .qodef-m-price-period',
	'.qodef-pricing-table .qodef-m-inner .qodef-m-price-period:before',
	'#ui-datepicker-div .ui-datepicker-current-day a',
	'.qodef-section-title .qodef-m-subtitle',
	'.qodef-stamp',
	'.qodef-stamp .qodef-m-centered-text',
	'.qodef-team .qodef-m-team-info .qodef-m-position',
	'.qodef-team .qodef-m-team-info .qodef-m-social-icons-group .qodef-icon-holder',
	'.qodef-workflow .qodef-e-subtitle',
	'.qodef-side-area-opener:hover',
	'.qodef-social-share li a',
	'.qodef-social-share.qodef-layout--dropdown .qodef-social-share-dropdown-opener',
	'.qodef-page-title .qodef-breadcrumbs',
	'.qodef-page-title .qodef-breadcrumbs a',
	'.qodef-page-title .qodef-breadcrumbs span',
	'.tribe-events-day .qodef-tribe-events-day .qodef-events-single-meta-icon',
	'.tribe-events-list.qodef-tribe-events-list .qodef-events-single-meta-icon',
	'#tribe-events .qodef-tribe-events .qodef-events-single-meta-icon',
	'.qodef-events-list .qodef-e-meta-icon',
	'.widget.qodef-author-info .qodef-m-country',
	'.widget.qodef-author-info .qodef-m-dob',
	'.widget.qodef-author-info .qodef-m-position',
	'.widget.qodef-author-info .qodef-m-social-icons a',
	'#qodef-woo-page .qodef-woo-product-mark',
	'.qodef-woo-shortcode .qodef-woo-product-mark',
	'#qodef-woo-page .qodef-woo-ratings .qodef-m-star',
	'.qodef-woo-shortcode .qodef-woo-ratings .qodef-m-star',
	'.woocommerce-page div.woocommerce .shop_table .order-total strong',
	'.woocommerce-account .woocommerce-MyAccount-navigation ul li.is-active a',
	'.woocommerce-account .woocommerce-MyAccount-content strong',
	'#qodef-woo-page .woocommerce-pagination .page-numbers.current',
	'#qodef-woo-page .woocommerce-pagination .page-numbers:hover',
	'body:not(.woocommerce-page) .qodef-woo-product-list:not(.qodef-woo-shortcode) .qodef-woo-product-inner:hover .qodef-woo-product-title',
	'body:not(.woocommerce-page) .qodef-woo-product-list:not(.qodef-woo-shortcode) .qodef-woo-ratings .qodef-m-star',
	'body:not(.woocommerce-page) .qodef-woo-product-list:not(.qodef-woo-shortcode) li.product-category .woocommerce-loop-category__title',
	'.qodef-woo-product-list .qodef-woo-product-categories a',
	'.qodef-woo-product-list .qodef-woo-product-categories .qodef-category-separator',
	'.qodef-woo-product-list .qodef-woo-product-tags a',
	'.qodef-woo-product-list .qodef-woo-product-tags .qodef-category-separator',
	'#qodef-woo-page .qodef-quantity-buttons .qodef-quantity-minus:hover',
	'#qodef-woo-page .qodef-quantity-buttons .qodef-quantity-plus:hover',
	'#qodef-woo-page.qodef--single .product_meta>.sku_wrapper .qodef-woo-meta-value',
	'#qodef-woo-page.qodef--single .product_meta .qodef-woo-meta-value a',
	'#qodef-woo-page.qodef--single .product_meta .qodef-woo-meta-value a:after',
	'#qodef-woo-page.qodef--single .woocommerce-Reviews .meta .woocommerce-review__published-date',
	'#qodef-woo-page.qodef--single #review_form form>.comment-form-rating a:before',
	'#qodef-woo-page.qodef--single #review_form form>.comment-form-rating a.active:after',
	'.widget.woocommerce .qodef-woo-ratings .qodef-m-star',
	'.widget.widget_shopping_cart .widget_shopping_cart_content ul li a:not(.remove):hover',
	'.widget.widget_layered_nav ul li.chosen a',
	'.widget.widget_products .qodef-woo-product-image:hover~.qodef-woo-product-content a',
	'.widget.widget_recent_reviews .qodef-woo-product-image:hover~.qodef-woo-product-content a',
	'.widget.widget_recently_viewed_products .qodef-woo-product-image:hover~.qodef-woo-product-content a',
	'.widget.widget_top_rated_products .qodef-woo-product-image:hover~.qodef-woo-product-content a',
	'.widget.widget_products .qodef-woo-product-title a:hover',
	'.widget.widget_recent_reviews .qodef-woo-product-title a:hover',
	'.widget.widget_recently_viewed_products .qodef-woo-product-title a:hover',
	'.widget.widget_top_rated_products .qodef-woo-product-title a:hover',
	'#qodef-page-footer .widget.widget_shopping_cart .widget_shopping_cart_content ul li a:not(.remove):hover',
	'#qodef-page-footer .widget.widget_layered_nav ul li.chosen a',
	'#qodef-page-footer .widget.widget_products .qodef-woo-product-image:hover~.qodef-woo-product-content a',
	'#qodef-page-footer .widget.widget_recent_reviews .qodef-woo-product-image:hover~.qodef-woo-product-content a',
	'#qodef-page-footer .widget.widget_recently_viewed_products .qodef-woo-product-image:hover~.qodef-woo-product-content a',
	'#qodef-page-footer .widget.widget_top_rated_products .qodef-woo-product-image:hover~.qodef-woo-product-content a',
	'#qodef-page-footer .widget.widget_products .qodef-woo-product-title a:hover',
	'#qodef-page-footer .widget.widget_recent_reviews .qodef-woo-product-title a:hover',
	'#qodef-page-footer .widget.widget_recently_viewed_products .qodef-woo-product-title a:hover',
	'#qodef-page-footer .widget.widget_top_rated_products .qodef-woo-product-title a:hover',
	'.qodef-header--vertical .wpb_widgetised_column .widget.widget_shopping_cart .widget_shopping_cart_content ul li a:not(.remove):hover',
	'.qodef-header--vertical .wpb_widgetised_column .widget.widget_layered_nav ul li.chosen a',
	'.qodef-header--vertical .wpb_widgetised_column .widget.widget_products .qodef-woo-product-image:hover~.qodef-woo-product-content a',
	'.qodef-header--vertical .wpb_widgetised_column .widget.widget_recent_reviews .qodef-woo-product-image:hover~.qodef-woo-product-content a',
	'.qodef-header--vertical .wpb_widgetised_column .widget.widget_recently_viewed_products .qodef-woo-product-image:hover~.qodef-woo-product-content a',
	'.qodef-header--vertical .wpb_widgetised_column .widget.widget_top_rated_products .qodef-woo-product-image:hover~.qodef-woo-product-content a',
	'.qodef-header--vertical .wpb_widgetised_column .widget.widget_products .qodef-woo-product-title a:hover',
	'.qodef-header--vertical .wpb_widgetised_column .widget.widget_recent_reviews .qodef-woo-product-title a:hover',
	'.qodef-header--vertical .wpb_widgetised_column .widget.widget_recently_viewed_products .qodef-woo-product-title a:hover',
	'.qodef-header--vertical .wpb_widgetised_column .widget.widget_top_rated_products .qodef-woo-product-title a:hover',
	'body #yith-quick-view-modal .qodef-woo-single-image .qodef-woo-product-mark',
	'body #yith-quick-view-modal .qodef-woo-ratings .qodef-m-star',
	'body #yith-quick-view-modal .qodef-quantity-buttons .qodef-quantity-minus:hover',
	'body #yith-quick-view-modal .qodef-quantity-buttons .qodef-quantity-plus:hover',
	'body #yith-quick-view-modal #yith-quick-view-close:hover',
	':not(.qodef-woo-product-wishlist-holder)>.yith-wcwl-add-to-wishlist .yith-wcwl-add-button a:before',
	':not(.qodef-woo-product-wishlist-holder)>.yith-wcwl-add-to-wishlist .yith-wcwl-wishlistaddedbrowse a:before',
	':not(.qodef-woo-product-wishlist-holder)>.yith-wcwl-add-to-wishlist .yith-wcwl-wishlistexistsbrowse a:before',
	'#qodef-top-area .qodef-woo-dropdown-cart .qodef-woo-dropdown-items a:hover',
	'.qodef-working-hours-list .qodef-e-day-icon',
	'.qodef-working-hours-list .qodef-e-time.qodef--closed',
	'.qodef-working-hours-list .qodef-m-footer-icon',
	'#qodef-membership-login-modal form label.required:after',
	'#qodef-membership-login-modal form .qodef-m-links-reset-password p',
	'#qodef-membership-login-modal .qodef-m-bottom .qodef-m-social-login button',
	'#qodef-membership-login-modal .qodef-m-links-register p',
	'.qodef-avp-holder .qodef-avp-subtitle',
	'.qodef-fullscreen-menu-holder nav.qodef-fullscreen-menu ul li ul li.current-menu-ancestor>a',
	'.qodef-fullscreen-menu-holder nav.qodef-fullscreen-menu ul li ul li.current-menu-item>a',
	'.qodef-fullscreen-menu-holder nav.qodef-fullscreen-menu ul li ul li a:hover',
	'.qodef-restaurant-menu-list.qodef-item-skin--light .qodef-e-description',
	'.qodef-testimonials-list.qodef-skin--light .qodef-e-author .qodef-e-author-job',
	'.qodef-reservation-form .qodef-e-icon-date',
	'.qodef-reservation-form .qodef-e-icon-time',
	'.qodef-reservation-form .qodef-e-icon-user',
	'.qodef-video-button .qodef-m-play-text .qodef-m-play-subtitle',
	'.qodef-woo-product-list.qodef-item-skin--light .qodef-woo-product-tags a',
	'.qodef-woo-product-list.qodef-item-skin--light .qodef-category-separator',
	'.qodef-woo-product-list.qodef-item-skin--light .qodef-woo-product-mark',
	'.qodef-header--vertical .wpb_widgetised_column .widget ul:not(.qodef-shortcode-list) li a',
	'.qodef-header--vertical .wpb_widgetised_column .widget ul:not(.qodef-shortcode-list) li',
	'.qodef-header--vertical .wpb_widgetised_column .widget.widget_product_tag_cloud .tagcloud a',
	'.qodef-header--vertical .wpb_widgetised_column .widget.widget_tag_cloud .tagcloud a',
	'.qodef-icon-list-item .qodef-icon-holder .qodef-icon',
	'#qodef-page-footer .widget.widget_recent_entries ul li .post-date',
	'#qodef-side-area .widget a',
	'.qodef-icon-with-text .qodef-icon-holder',
	'#qodef-page-footer .widget a:hover',
	'#qodef-page-footer .widget.widget_recent_entries ul li a:hover',
	'.widget ul:not(.qodef-shortcode-list) li a',
	'.widget ul:not(.qodef-shortcode-list) li',
	'.widget.widget_recent_entries ul li .post-date',
	'.widget.widget_product_tag_cloud .tagcloud a',
	'.widget.widget_tag_cloud .tagcloud a'
);
$color_important_selector            = array(
	'#qodef-page-footer-bottom-area .widget a',
	'.qodef-header-navigation ul li.qodef-menu-item--narrow ul li a:hover .qodef-menu-item-inner',
	'.qodef-header--centered #qodef-page-header>div:not(.qodef-header-sticky) .widget:hover .qodef-m-opener-count',
	'.qodef-header--divided #qodef-page-header>div:not(.qodef-header-sticky) .widget:hover .qodef-m-opener-count',
	'.qodef-header--standard #qodef-page-header>div:not(.qodef-header-sticky) .widget:hover .qodef-m-opener-count',
	'.qodef-header--centered.qodef-header--dark #qodef-page-header>div:not(.qodef-header-sticky) .widget:hover .qodef-m-opener-count',
	'.qodef-header--divided.qodef-header--dark #qodef-page-header>div:not(.qodef-header-sticky) .widget:hover .qodef-m-opener-count',
	'.qodef-header--standard.qodef-header--dark #qodef-page-header>div:not(.qodef-header-sticky) .widget:hover .qodef-m-opener-count',
	'.qodef-header-navigation ul li.qodef-menu-item--wide .qodef-drop-down-second .qodef-drop-down-second-inner>ul>li>a span',
	'.qodef-header-navigation ul li.qodef-menu-item--wide .qodef-drop-down-second .qodef-drop-down-second-inner ul li a:hover span',
	'.qodef-woo-product-list .qodef-woo-product-button-holder>:hover',
	'.qodef-woo-product-list .qodef-woo-product-button-holder>:hover *',
	'.qodef-woo-dropdown-cart .qodef-e-title a:hover',
	'.qodef-woo-dropdown-cart .qodef-e-remove:hover',
	'.qodef-login-opener-widget .qodef-logged-in-user .qodef-m-navigation-item .qodef-e-link:hover',
	'.qodef-header--vertical .wpb_widgetised_column .widget.widget_product_tag_cloud .tagcloud a:after',
	'.qodef-header--vertical .wpb_widgetised_column .widget.widget_tag_cloud .tagcloud a:after',
	'#qodef-top-area .widget a:hover',
	'.qodef-section-title .qodef-m-subtitle',
	'.qodef-icon-with-text .qodef-icon-holder',
	'.qodef-pricing-table .qodef-m-inner .qodef-m-price .qodef-m-price-currency',
	'.qodef-banner .qodef-m-content .qodef-m-content-inner .qodef-m-text-field',
	'.qodef-icon-with-text .qodef-icon-holder'
);
$background_color_selector           = array(
	'button[type=submit]',
	'input[type=submit]',
	'.swiper-pagination-bullets .swiper-pagination-bullet-active:after',
	'.qodef-blog .mejs-container .mejs-controls .mejs-time-rail .mejs-time-total .mejs-time-current',
	'.qodef-blog .mejs-container .mejs-controls .mejs-horizontal-volume-slider .mejs-horizontal-volume-total .mejs-horizontal-volume-current',
	'#qodef-back-to-top .qodef-back-to-top-icon',
	'#qodef-author-info .qodef-m-social-icons a:hover',
	'.qodef-header--centered #qodef-page-header>div:not(.qodef-header-sticky) .widget:hover',
	'.qodef-header--divided #qodef-page-header>div:not(.qodef-header-sticky) .widget:hover',
	'.qodef-header--standard #qodef-page-header>div:not(.qodef-header-sticky) .widget:hover',
	'.qodef-header--centered.qodef-header--light #qodef-page-header>div:not(.qodef-header-sticky) .widget:hover .qodef-lines .qodef-line',
	'.qodef-header--divided.qodef-header--light #qodef-page-header>div:not(.qodef-header-sticky) .widget:hover .qodef-lines .qodef-line',
	'.qodef-header--standard.qodef-header--light #qodef-page-header>div:not(.qodef-header-sticky) .widget:hover .qodef-lines .qodef-line',
	'.qodef-header--centered.qodef-header--dark #qodef-page-header>div:not(.qodef-header-sticky) .widget:hover',
	'.qodef-header--divided.qodef-header--dark #qodef-page-header>div:not(.qodef-header-sticky) .widget:hover',
	'.qodef-header--standard.qodef-header--dark #qodef-page-header>div:not(.qodef-header-sticky) .widget:hover',
	'.qodef-button.qodef-layout--filled.qodef-html--link',
	'.qodef-icon-holder.qodef-layout--circle',
	'.qodef-icon-holder.qodef-layout--square',
	'#ui-datepicker-div .ui-datepicker-today',
	'.qodef-team .qodef-m-team-info .qodef-m-social-icons-group .qodef-icon-holder:hover',
	'.qodef-workflow .qodef-e-workflow-item-inner:after',
	'.tribe-events-month.qodef-tribe-events-month .tribe-events-calendar tbody td.tribe-events-has-events>div',
	'.tribe-events-month.qodef-tribe-events-month .tribe-events-calendar tbody td.tribe-events-has-events>div>a',
	'#tribe-events .qodef-tribe-events .tribe-events-button',
	'.widget.qodef-author-info .qodef-m-social-icons a:hover',
	'#qodef-woo-page .added_to_cart',
	'#qodef-woo-page .button',
	'.qodef-woo-shortcode .added_to_cart',
	'.qodef-woo-shortcode .button',
	'.woocommerce-page div.woocommerce>.return-to-shop a',
	'.woocommerce-account .woocommerce-MyAccount-content .woocommerce-Address-title a',
	'.woocommerce-account .button',
	'.widget.woocommerce .button',
	'.widget.woocommerce button',
	'.widget.widget_price_filter .price_slider_wrapper .ui-widget-content .ui-slider-handle',
	'.widget.widget_price_filter .price_slider_wrapper .ui-widget-content .ui-slider-range',
	'#qodef-page-footer .widget.widget_price_filter .price_slider_wrapper .ui-widget-content .ui-slider-handle',
	'#qodef-page-footer .widget.widget_price_filter .price_slider_wrapper .ui-widget-content .ui-slider-range',
	'.qodef-header--vertical .wpb_widgetised_column .widget.widget_price_filter .price_slider_wrapper .ui-widget-content .ui-slider-handle',
	'.qodef-header--vertical .wpb_widgetised_column .widget.widget_price_filter .price_slider_wrapper .ui-widget-content .ui-slider-range',
	'#yith-wcwl-form .shop_table td.product-add-to-cart a',
	'.qodef-woo-dropdown-cart .qodef-m-action .qodef-m-action-link:nth-child(1)',
	'#qodef-membership-login-modal .qodef-m-bottom .qodef-m-social-login button:hover',
	'.qodef-blog .mejs-container .mejs-controls .mejs-time-rail>*>:not(.mejs-time-float)>*'
);
$background_color_important_selector = array(
	'.swiper-pagination-progressbar .swiper-pagination-progressbar-fill',
	'.qodef-fullscreen-menu-opener.qodef-fullscreen-menu-opener--predefined:hover .qodef-line',
	'.qodef-header--centered.qodef-header--light #qodef-page-header>div:not(.qodef-header-sticky) .widget:hover .qodef-m-opener-count',
	'.qodef-header--divided.qodef-header--light #qodef-page-header>div:not(.qodef-header-sticky) .widget:hover .qodef-m-opener-count',
	'.qodef-header--standard.qodef-header--light #qodef-page-header>div:not(.qodef-header-sticky) .widget:hover .qodef-m-opener-count',
	'#tribe-events-bar .qodef-tribe-events-bar input[type=submit]',
	'.post-type-archive-tribe_events .datepicker .active',
	'.qodef-woo-product-list.qodef-image-opacity-hover .qodef-woo-product-button-holder>:hover',
	'.qodef-woo-dropdown-cart .qodef-m-opener .qodef-m-opener-count',
	'.qodef-progress-bar.qodef-layout--line .proggress'

);
$border_color_selector               = array(
	'#qodef-back-to-top .qodef-back-to-top-icon',
	'#qodef-author-info .qodef-m-social-icons a:hover',
	'.qodef-header--centered #qodef-page-header>div:not(.qodef-header-sticky) .widget:hover',
	'.qodef-header--divided #qodef-page-header>div:not(.qodef-header-sticky) .widget:hover',
	'.qodef-header--standard #qodef-page-header>div:not(.qodef-header-sticky) .widget:hover',
	'.qodef-header--centered.qodef-header--dark #qodef-page-header>div:not(.qodef-header-sticky) .widget:hover',
	'.qodef-header--divided.qodef-header--dark #qodef-page-header>div:not(.qodef-header-sticky) .widget:hover',
	'.qodef-header--standard.qodef-header--dark #qodef-page-header>div:not(.qodef-header-sticky) .widget:hover',
	'.qodef-team .qodef-m-team-info .qodef-m-social-icons-group .qodef-icon-holder:hover',
	'.widget.qodef-author-info .qodef-m-social-icons a:hover',
	'#qodef-page-footer .widget.widget_product_search input:focus',
	'#qodef-membership-login-modal .qodef-m-bottom .qodef-m-social-login button:hover'
);
$border_color_important_selector     = array( '.qodef-woo-product-list.qodef-image-opacity-hover .qodef-woo-product-button-holder>:hover' );
